### ISSUE TITLE
Image/Avatar FileNotFoundException

### ISSUE THREAD

**Issue by Itsusinn** [gnuf0rce/github-helper#10]
```
2022-07-25 19:04:38 W/github-helper: HttpClient Ignore java.io.FileNotFoundException: /root/mcl/data/io.github.gnuf0rce.github-helper/image/avatar/Itsusinn.50.jpeg (No such file or directory)
2022-07-25 19:04:38 W/github-helper: HttpClient Ignore java.io.FileNotFoundException: /root/mcl/data/io.github.gnuf0rce.github-helper/image/avatar/Itsusinn.50.jpeg (No such file or directory)
2022-07-25 19:04:39 W/github-helper: HttpClient Ignore java.io.FileNotFoundException: /root/mcl/data/io.github.gnuf0rce.github-helper/image/avatar/Itsusinn.50.jpeg (No such file or directory)
2022-07-25 19:04:39 W/github-helper: HttpClient Ignore java.io.FileNotFoundException: /root/mcl/data/io.github.gnuf0rce.github-helper/image/avatar/Itsusinn.50.jpeg (No such file or directory)
2022-07-25 19:04:39 W/github-helper: Exception in executing command `[mirai:source:ids=[37813], internalIds=[1013329109], from group 1802888838 to 66788843 at 1658888073]/repo-release test MeowCat-Studio/telegram-message-source OLD`
java.io.FileNotFoundException: /root/mcl/data/io.github.gnuf0rce.github-helper/image/avatar/Itsusinn.50.jpeg (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
        at github-helper-1.2.2.jar//io.github.gnuf0rce.mirai.github.GitHubMessageKt$avatar$file$1.invokeSuspend(GitHubMessage.kt:212)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Itsusinn** [comment]
Config:
```
# Proxy Format http://127.0.0.1:8080 or socks://127.0.0.1:1080
proxy: 'http://127.0.0.1:7890'
# GitHub Token by https://github.com/settings/tokens
github_token: 'ghp_MxDGsp3lra*********2u953A6Qd3'
# Replier Reply Message Type
reply_type: TEXT
# Http Timeout Second
timeout: 30
# 放行活跃等级（百分制）
percentage_member_join: 0
# 放行活跃等级（百分制）
percentages: 
  12345: 49
# 加群提醒
sign_member_join: 新人入群请看群公告
# with https://github-readme-stats.vercel.app/
github_readme_stats: 
  show_icons: true
  theme: tokyonight
  count_private: true
  include_all_commits: true
```

**Comment by cssxsh** [comment]
某次更新误把创建 avatar 文件夹的代码删了，你可以手动创建一下
