### ISSUE TITLE
UnknownHostException 报错

### ISSUE THREAD

**Issue by Yurinann** [gnuf0rce/github-helper#13]
```
2022-12-25 16:30:45 W/github-helper: repo-commit with YuriProjects/MegaWalls run fail
java.net.UnknownHostException: 127.0.0.1: NXDOMAIN
        at github-helper-1.2.9.mirai2.jar[private]//okhttp3.dnsoverhttps.DnsRecordCodec.decodeAnswers(DnsRecordCodec.kt:74)
        at github-helper-1.2.9.mirai2.jar[private]//okhttp3.dnsoverhttps.DnsOverHttps.readResponse(DnsOverHttps.kt:231)
        at github-helper-1.2.9.mirai2.jar[private]//okhttp3.dnsoverhttps.DnsOverHttps.processResponse(DnsOverHttps.kt:153)
        at github-helper-1.2.9.mirai2.jar[private]//okhttp3.dnsoverhttps.DnsOverHttps.access$processResponse(DnsOverHttps.kt:55)
        at github-helper-1.2.9.mirai2.jar[private]//okhttp3.dnsoverhttps.DnsOverHttps$executeRequests$1.onResponse(DnsOverHttps.kt:133)
        at github-helper-1.2.9.mirai2.jar[private]//okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

您好，请问这是什么原因？在网上没有查询到类似的问题。

**Comment by cssxsh** [comment]
是否频繁出现
如果不是，那可能只是偶尔出现的网络异常，不用在意

**Comment by Yurinann** [comment]
频繁出现，至今还未成功连接到 Github 服务。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月27日(周二) 中午12:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gnuf0rce/github-helper] UnknownHostException 报错 (Issue #13)




 
是否频繁出现
 如果不是，那可能只是偶尔出现的网络异常，不用在意

**Comment by cssxsh** [comment]
是否改动了默认配置

**Comment by Yurinann** [comment]
proxy使用的https，添加了自己的token，其他均未改动会出现此问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月27日(周二) 中午12:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gnuf0rce/github-helper] UnknownHostException 报错 (Issue #13)




 
是否改动了默认配置

**Comment by Yurinann** [comment]
回答您这个问题的时候，我突然想到了一个原因。。自测了一下，是代理的问题，不好意思，打扰了。
