### ISSUE TITLE
`merge_commit_sha` 字段可能为 `null`

### ISSUE THREAD

**Issue by jie65535** [gnuf0rce/github-helper#15]
## 版本
- Mirai v2.14.0
- GithubHelper v1.2.11

## 日志
```log
2023-04-13 11:18:11 W/github-helper: repo-pull with Grasscutters/Grasscutter run fail
io.ktor.serialization.JsonConvertException: Illegal input
        at github-helper-1.2.11.mirai2.jar[private]//io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:79)
        at github-helper-1.2.11.mirai2.jar[private]//io.ktor.serialization.kotlinx.KotlinxSerializationConverter$deserialize$1.invokeSuspend(KotlinxSerializationConverter.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 3106: Unexpected 'null' value instead of string literal at path: $[0].merge_commit_sha
JSON input: .....,
    "merge_commit_sha": null,
    "assignee": null,
    "a.....
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:528)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:526)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeStringLenientNotNull(AbstractJsonLexer.kt:374)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:290)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeStringElement(AbstractDecoder.kt:58)
        at github-helper-1.2.11.mirai2.jar//io.github.gnuf0rce.github.entry.Pull$$serializer.deserialize(Pull.kt:16)
        at github-helper-1.2.11.mirai2.jar//io.github.gnuf0rce.github.entry.Pull$$serializer.deserialize(Pull.kt:16)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:111)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:537)
        at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
        at github-helper-1.2.11.mirai2.jar[private]//io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:71)
        ... 7 more
```

**Comment by cssxsh** [comment]
给具体的测试例子

**Comment by jie65535** [comment]
这是仅有的相关日志，其中的信息应该足够分析，这是由 `Pull` 更新的定时任务触发的，订阅的仓库是 [Grasscutter](https://github.com/Grasscutters/Grasscutter)，大约在 `2023-04-13 11:18` 时间更新的PR，查找Pulls仅有[这个PR](https://github.com/Grasscutters/Grasscutter/pull/2110)符合条件。

我不清楚还能提供哪些信息？
