### ISSUE TITLE
java.lang.IllegalStateException: Qian-F/Miracles-Journey:pack no matches ([\w-.]+)/([\w-.]+)

### ISSUE THREAD

**Issue by QianFuv** [gnuf0rce/github-helper#18]
### 环境

- Win10
- Overflow
- LLOnebot

### 网络

访问 Github 正常

![image-20240502214955593](https://cdn.sa.net/2024/05/02/r4aVvdJbSlCBeEY.png)

### 问题

- 使用常规命令添加 `Commit` 监听后报错且无法正常推送消息

    - 命令：`/repo-commit add Qian-F/Miracles-Journey`

    - 报错：

        ```
        2024-05-02 21:38:20 W/github-helper: repo-commit with Qian-F/Miracles-Journey api fail, ApiError(documentationUrl=https://docs.github.com/rest/commits/commits#list-commits, message=Not Found, errors=[])
        ```

- 使用相关 [Issue](https://github.com/gnuf0rce/github-helper/issues/17) 中提到的 [命令](https://github.com/gnuf0rce/github-helper/issues/17#issuecomment-2087979814) 添加 Commit 监听时报错

    - 命令：`/repo-commit add Qian-F/Miracles-Journey:pack`

    - 报错：

        ```
        2024-05-02 21:45:44 W/github-helper: Exception in executing command `[mirai:source:ids=[-2147483534], internalIds=[-2147483534], from friend 576765349 to 1741755095 at 1714657]/repo-commit add Qian-F/Miracles-Journey:pack`
         command owned by github-helper v1.5.0 with Friend(576765349)
        java.lang.IllegalStateException: Qian-F/Miracles-Journey:pack no matches ([\w-.]+)/([\w-.]+)
                at github-helper-1.5.0.mirai2.jar//io.github.gnuf0rce.mirai.github.GitHubSubscriber.add(GitHubSubscriber.kt:60)
                at github-helper-1.5.0.mirai2.jar//io.github.gnuf0rce.mirai.github.command.GitHubRepoCommitCommand.add(GitHubRepoCommitCommand.kt:36)
                at github-helper-1.5.0.mirai2.jar//io.github.gnuf0rce.mirai.github.command.GitHubRepoCommitCommand.add$default(GitHubRepoCommitCommand.kt:35)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
                at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
                at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
                at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
                at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
                at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
                at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
                at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
                at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
                at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
                at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
                at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
                at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
                at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:126)
                at chat-command-0.6.0.mirai2.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:98)
                at chat-command-0.6.0.mirai2.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:66)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        ```

**Comment by QianFuv** [comment]
使用版本为：https://github.com/gnuf0rce/github-helper/actions/runs/8905870321
