### ISSUE TITLE
添加repo-commit报错

### ISSUE THREAD

**Issue by RealSeek** [gnuf0rce/github-helper#6]
错误信息

```
2022-05-10 20:20:02 W/github-helper: repo-commit with RealSeek/Vampire run fail
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 8837: Expected start of the object '{', but had ' ' instead
JSON input: .....4e588/comments",
    "author": null,
    "committer": null,
.....
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:524)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:221)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:204)
        at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:74)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:41)
        at github-helper-1.1.10.mirai.jar//io.github.gnuf0rce.github.entry.User$$serializer.deserialize(User.kt:6)
        at github-helper-1.1.10.mirai.jar//io.github.gnuf0rce.github.entry.User$$serializer.deserialize(User.kt:6)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at github-helper-1.1.10.mirai.jar//io.github.gnuf0rce.github.entry.Commit$$serializer.deserialize(Commit.kt:6)
        at github-helper-1.1.10.mirai.jar//io.github.gnuf0rce.github.entry.Commit$$serializer.deserialize(Commit.kt:6)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
        at github-helper-1.1.10.mirai.jar//io.ktor.client.features.json.serializer.KotlinxSerializer.read(KotlinxSerializer.kt:37)
        at github-helper-1.1.10.mirai.jar//io.ktor.client.features.json.JsonSerializer$DefaultImpls.read(JsonSerializer.kt:31)
        at github-helper-1.1.10.mirai.jar//io.ktor.client.features.json.serializer.KotlinxSerializer.read(KotlinxSerializer.kt:20)
        at github-helper-1.1.10.mirai.jar//io.ktor.client.features.json.JsonFeature$Feature$install$2.invokeSuspend(JsonFeature.kt:161)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by cssxsh** [comment]
可能是来自非GitHub提交的 commit，导致没有一个对应的github账号 导致 null

with https://github.com/gnuf0rce/github-helper/commit/d2a42563f0638e10447ef62d9a15b09c9ed72dc1 修复

**Comment by RealSeek** [comment]
> 可能是来自 GitHub 提交的提交，导致没有一个的 github 账号返回 null
> 
> 用[d2a4256](https://github.com/gnuf0rce/github-helper/commit/d2a42563f0638e10447ef62d9a15b09c9ed72dc1)修复

编译报错

github-helper\src\main\kotlin\io\github\gnuf0rce\mirai\plugin\GitHubMessage.kt: (349, 56): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type User?

**Comment by cssxsh** [comment]
啊，我之后会发布新版本，不需要你处理

**Comment by RealSeek** [comment]
好的 麻烦作者了

**Comment by cssxsh** [comment]
with https://github.com/gnuf0rce/github-helper/releases/tag/v1.1.11-M1

**Comment by RealSeek** [comment]
> with https://github.com/gnuf0rce/github-helper/releases/tag/v1.1.11-M1

是需要依赖插件么

```
2022-05-14 15:56:35 W/github-helper: 发送信息失败
java.lang.NoClassDefFoundError: org/openqa/selenium/WebDriverException
        at github-helper-1.1.11-M1.mirai.jar//io.github.gnuf0rce.mirai.plugin.GitHubSubscriber.sendMessage(GitHubSubscriber.kt:98)
        at github-helper-1.1.11-M1.mirai.jar//io.github.gnuf0rce.mirai.plugin.GitHubSubscriber.access$sendMessage(GitHubSubscriber.kt:11)
        at github-helper-1.1.11-M1.mirai.jar//io.github.gnuf0rce.mirai.plugin.GitHubSubscriber$launch$1.invokeSuspend(GitHubSubscriber.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.WebDriverException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.loadClass(JvmPluginClassLoader.kt:347)
        ... 27 more
```

**Comment by cssxsh** [comment]
> WebDriverException

这是订阅 repo-issue 出现的问题？

**Comment by RealSeek** [comment]
> WebDriverException

看样子是发送消息出现的问题
我是订阅repo-commit 后提交几个测试commit 后出现的问题

**Comment by cssxsh** [comment]
> NoClassDefFoundError

我在想为什么会触发这个， commit 是用不到浏览器的
如果你急用的话，可以先安装 https://github.com/cssxsh/mirai-selenium-plugin

**Comment by RealSeek** [comment]
好的 安装完后可以正常发送了 
另外希望可以支持自定义推送的格式 ~~默认的感觉太乱了~~

**Comment by cssxsh** [comment]
with https://github.com/gnuf0rce/github-helper/releases/tag/v1.2.0-RC

更新了推送的格式
